[package]
name = "dotfilesctl"
version = "0.1.0"
authors = ["Lars Hupel <lars@hupel.info>"]

[dependencies]
clap = "^2.29"
env_logger = "^0.5"
failure = "^0.1"
log = "^0.4"
notify = "^4.0"
notify-rust = "^3"
pretty_env_logger = "^0.2"
proptest = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
tempdir = "^0.3"
toml = "^0.4"
xdg = "^2.1"
